services:
  sporteasy-calendar-connector:
    image: sporteasy-calendar-connector
    build:
      context: ./
    ports:
      - "5000:5000"
    volumes:
      - ./sporteasy-calendar-connector-logs:/logs
      # Ensure this file exists before running. `touch database.db` is sufficient.
      - type: bind
        source: ./database.db
        target: /app/database.db
    restart: unless-stopped
